name: CI

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests (PRs)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          pytest -q -m "focus_group or solution_discovery" || pytest -q -k "focus_group or solution_discovery"
      - name: Run full suite (main)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          pytest -q
